name: upm-subtree-split

on:
  push:
    branches:
    - main
jobs:
  upm-subtree-split:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: upm subtree split
      run: |
        git subtree split --prefix="OpenAI/Packages/com.openai.unity" -b upm
        git push -u origin upm --force
